FROM amazonlinux

WORKDIR /app

COPY . /app

RUN yum install -y httpd && \
	amazon-linux-extras install -y php7.2 && \
	yum install -y php php-pgsql 

COPY ./setup/crm/crm.conf /etc/httpd/conf.d/

CMD ["apachectl", "-D", "FOREGROUND"]

