INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (1,10,'Peninsular Range (E)','#6A1B9A');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (2,11,'Gulf Rifted Margin','#D84315');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (3,6,'Peninsular Range (W)','#7B1FA2');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (4,36,'Oceanic Crust','#6C2DC7');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (5,34,'Accretionary Prism(S)','#347C17');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (6,27,'Nicolas Terrane','#FFD801');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (7,25,'Inner Borderland Rift','#FFA62F');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (8,13,'Mojavia','#3090C7');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (9,31,'Rift Axis 1','#D462FF');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (10,33,'Rift Axis 3','#D462FF');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (11,7,'Basin and Range','#D84315');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (12,28,'Rift Axis 2','#D462FF');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (13,12,'San Gabriel','#3090C7');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (14,23,'Western Transverse Ranges','#FFD801');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (15,16,'Salinia','#3090C7');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (16,34,'Accretionary Prism(N)','#347C17');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (17,29,'San Francisco Bay','#347C17');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (18,18,'Great Valley','#FFD801');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (19,9,'Southern Walker Lane','#FF6F00');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (20,3,'Sierra Nevada (E)','#B041FF');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (21,5,'Sierra Nevada (W)','#4A148C');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (22,20,'Santa Maria Rift','#FFA62F');
INSERT INTO CRM_REGION_tb ("domain_id","gfm_region_tb_gid","name","color") VALUES (23,4,'Colorado Plateau','#614051');
