INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (1,'WBR','Western Basin and Range','#D84315');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (2,'SN','Sierra Nevada','#B041FF');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (3,'CCR','Central Coast Ranges','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (4,'PR','Peninsular Ranges','#7B1FA2');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (5,'ST','Salton Trough','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (6,'WTR','Western Transverse Ranges','#FFD801');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (7,'LA','Los Angeles','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (8,'SG','San Gabriels','#3090C7');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (9,'MD','Mojave Desert','#3090C7');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (10,'GV','Great Valley','#FFD801');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (11,'ETR','Eastern Transverse Ranges','#FFD801');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (12,'iST','Inner Salton Trough','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (13,'iCB','Inner Continental Borderland','#FFA62F');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (14,'VB','Ventura Basin','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (15,'Ocean','Ocean','#6C2DC7');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (16,'CCRext','CCR extension','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (17,'GVext','GV extension','#FFD801');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (18,'SNext','SN extension','#B041FF');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (19,'WBRext','WBR extension','#D84315');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (20,'SText','ST extension','#347C17');
INSERT INTO CTM_REGION_tb ("domain_id","name","full_name","color") VALUES (21,'PRext','PR extension','#7B1FA2');
